name: 'create-dmg-action-fixed-icon'
description: 'Create DMG for macOS (Fixed icon location)'
author: 'QQxiaoming(2014500726@smail.xtu.edu.cn)'
inputs:
  srcdir:
    description: 'source dir'
    default: 'srcdir'
  name:
    description: 'dmg name'
    default: 'target'
runs:
  using: 'node16'
  main: 'dist/index.js'
